
import React,{FormEvent, useState} from 'react';
const LaborPartyCandidates = {
    "Algester": "Leeanne Enoch",
    "Aspley": "Bart Mellish",
    "Bancroft": "Chris Whiting",
    "Barron River": "Craig Crawford",
    "Bonney": "Kyle Kelly-Collins",
    "Broadwater": "Tamika Hicks",
    "Bulimba": "Di Farmer",
    "Bundaberg": "Tom Smith",
    "Bundamba": "Lance McCallum",
    "Burdekin": "Anne Baker",
    "Burleigh": "Claire Carlin",
    "Cairns": "Michael Healy",
    "Caloundra": "Jason Hunt",
    "Capalaba": "Don Brown",
    "Chatsworth": "Lisa ODonnell",
    "Cook": "Cynthia Lui",
    "Coomera": "Chris Johnson",
    "Cooper": "Jonty Bush",
    "Currumbin": "Nathan Fleury",
    "Ferny Grove": "Mark Furner",
    "Gaven": "Meaghan Scanlon",
    "Gladstone": "Glenn Butcher",
    "Greenslopes": "Joe Kelly",
    "Gympie": "Lachlan Anderson",
    "Hervey Bay": "Adrian Tantari",
    "Inala": "Margie Nightingale",
    "Ipswich": "Jennifer Howard",
    "Ipswich West": "Wendy Bourne",
    "Jordan": "Charis Mullen",
    "Keppel": "Brittany Lauga",
    "Kurwongbah": "Shane King",
    "Logan": "Linus Power",
    "Lytton": "Joan Pease",
    "Macalister": "Melissa McMahon",
    "Mackay": "Julieanne Gilbert",
    "Maiwar": "Susan Irvine",
    "Mansfield": "Corrine McMillan",
    "Maroochydore": "Naomi McQueen",
    "Maryborough": "Bruce Saunders",
    "McConnel": "Grace Grace",
    "Mermaid Beach": "Joseph Shiels",
    "Miller": "Mark Bailey",
    "Moggill": "Eric Richman",
    "Morayfield": "Mark Ryan",
    "Mount Ommaney": "Jessica Pugh",
    "Mudgeeraba": "Sophie Lynch",
    "Mulgrave": "Curtis Pitt",
    "Mundingburra": "Les Walker",
    "Murrumba": "Steven Miles",
    "Nicklin": "Robert Skelton",
    "Ninderry": "Jo Justo",
    "Noosa": "Mark Denham",
    "Nudgee": "Leanne Linard",
    "Pine Rivers": "Nikki Boyd",
    "Pumicestone": "Ali King",
    "Redcliffe": "Kassandra Hall",
    "Redlands": "Kim Richards",
    "Rockhampton": "Craig Marshall",
    "Sandgate": "Bisma Asif",
    "South Brisbane": "Barbara O'Shea",
    "Southport": "Letitia Del Fabbrio",
    "Springwood": "Mick de Brenni",
    "Stafford": "Jimmy Sullivan",
    "Stretton": "James Martin",
    "Surfers Paradise": "James Knight",
    "Theodore": "Rita Anwari",
    "Thuringowa": "Aaron Harper",
    "Toohey": "Peter Russo",
    "Toowoomba South": "Susan Krause",
    "Townsville": "Scott Stewart",
    "Waterford": "Shannon Fentiman",
    "Woodridge": "Cameron Dick"
  }
  const LNPCandidates= {
    "Aspley": "Amanda Cooper",
    "Bancroft": "Rob Barridge",
    "Barron River": "Bree James",
    "Bonney": "Sam O'Connor",
    "Broadwater": "David Crisafulli",
    "Buderim": "Brent Mickelberg",
    "Bundaberg": "Bree Watson",
    "Burdekin": "Dale Last",
    "Burleigh": "Hermann Vorster",
    "Burnett": "Stephen Bennett",
    "Cairns": "Yolonde Entsch",
    "Callide": "Bryson Head",
    "Caloundra": "Kendall Morton",
    "Chatsworth": "Steve Minnikin",
    "Clayfield": "Tim Nicholls",
    "Condamine": "Pat Weir",
    "Cook": "David Kempton",
    "Coomera": "Michael Crandon",
    "Currumbin": "Laura Gerber",
    "Everton": "Tim Mander",
    "Ferny Grove": "Nelson Savanh",
    "Gaven": "Bianca Stone",
    "Glass House": "Andrew Powell",
    "Greenslopes": "Andrew Newbold",
    "Gregory": "Sean Dillon",
    "Gympie": "Tony Perrett",
    "Hervey Bay": "David Lee",
    "Hill": "Cameron McCollum",
    "Inala": "Trang Yen",
    "Ipswich West": "Georgia Toft",
    "Kawana": "Jarrod Bleijie",
    "Keppel": "Nigel Hutton",
    "Kurwongbah": "Tanya McKewen",
    "Lockyer": "Jim McDonald",
    "Macalister": "Rob Van Manen",
    "Mackay": "Nigel Dalton",
    "Maiwar": "Natasha Winters",
    "Mansfield": "Pinky Singh",
    "Maroochydore": "Fiona Simpson",
    "Maryborough": "John Barounis",
    "McConnel": "Christien Duffey",
    "Mermaid Beach": "Ray Stevens",
    "Mirani": "Glen Kelly",
    "Moggill": "Christian Rowan",
    "Mount Ommaney": "Lisa Baillie",
    "Mudgeeraba": "Ros Bates",
    "Mundingburra": "Janelle Poole",
    "Murrumba": "Gary Fulton",
    "Nanango": "Deb Frecklington",
    "Nicklin": "Marty Hunt",
    "Ninderry": "Dan Purdie",
    "Noosa": "Clare Stewart",
    "Oodgeroo": "Amanda Stoker",
    "Pine Rivers": "Dean Clements",
    "Pumicestone": "Ariana Doolan",
    "Redcliffe": "Kerri-Anne Dooley",
    "Redlands": "Rebecca Young",
    "Rockhampton": "Donna Kirkland",
    "Scenic Rim": "Jon Krause",
    "Southern Downs": "James Lister",
    "Southport": "Rob Molhoek",
    "Springwood": "Susanna Damianopoulos",
    "Stafford": "Fiona Hammond",
    "Surfers Paradise": "John-Paul Langbroek",
    "Theodore": "Mark Boothman",
    "Thuringowa": "Natalie Marr",
    "Toohey": "Taylor Hull",
    "Toowoomba North": "Trevor Watts",
    "Toowoomba South": "David Janetzki",
    "Townsville": "Adam Baillie",
    "Warrego": "Ann Leahy",
    "Whitsunday": "Amanda Camm"
  }
  const greensPartyCandidate = {

    "Algester": "Andrea Wildin",
    "Bulimba": "Linda Barry",
    "Bundamba": "Tracey Nayler",
    "Burleigh": "Hunter Grove-McGrath",
    "Cairns": "Josh Holt",
    "Clayfield": "Jaimyn Mayer",
    "Cooper": "Katinka Winston-Allom",
    "Currumbin": "Braden Smith",
    "Everton": "Brent McDowall",
    "Ferny Grove": "Elizabeth McAulay",
    "Greenslopes": "Rebecca White",
    "Ipswich West": "Mark Delaney",
    "Lockyer": "Eleanor Sharman",
    "Maiwar": "Michael Berkman",
    "McConnel": "Holstein Wong",
    "Miller": "Liam Flenady",
    "Moggill": "Andrew Kidd",
    "Murrumba": "Deklan Green",
    "Nudgee": "Jim Davies",
    "Redcliffe": "Will Simon",
    "Sandgate": "Rachel Kennedy",
    "South Brisbane": "Amy MacMahon",
    "Stafford": "Jessica Lane",
    "Stretton": "Ahmed Abdulhamed",
    "Toohey": "Melissa McArdle",
    "Townsville": "Benjamin Tiley"
  }
  const oneNationPartyCandidates= {

    "Barron River": "Peter Eicens",
    "Bonney": "Scott Philip",
    "Broadwater": "Steven Whitehead",
    "Burdekin": "Andrew Elborne",
    "Burnett": "Arno Blank",
    "Cairns": "Geena Court",
    "Callide": "Christopher O'Callaghan",
    "Clayfield": "Michelle Wilde",
    "Cook": "Peter Campion",
    "Coomera": "Nick Muir",
    "Gaven": "Sandy Roach",
    "Gladstone": "Andrew Jackson",
    "Gympie": "Katy McCallum",
    "Hervey Bay": "Quinn Hendry",
    "Hill": "Brenda Turner",
    "Hinchinbrook": "Ric Daubert",
    "Keppel": "James Ashby",
    "Lockyer": "Corey West",
    "Logan": "Brettlyn Neal",
    "Lytton": "David White",
    "Mackay": "Kylee Stanton",
    "Maroochydore": "Kyle Haley",
    "Maryborough": "Taryn Gillard",
    "Mermaid Beach": "Roger Marquass",
    "Mirani": "Stephen Andrew",
    "Morayfield": "Rodney Hansen",
    "Mulgrave": "Michael McInnes",
    "Mundingburra": "Robyn Fitzgerald",
    "Nanango": "Adam Maslen",
    "Pumicestone": "Samuel Beaton",
    "Rockhampton": "David Bond",
    "Scenic Rim": "Wayne Ziebarth",
    "Southern Downs": "Liz Suduk",
    "Southport": "David Vaughan",
    "Springwood": "Glen Cookson",
    "Surfers Paradise": "Mark Jaric",
    "Thuringowa": "Matthew Millar (suspended)",
    "Whitsunday": "Julie Hall"
  }
  const KAPPartyCandidates = {

    "Algester": "Rhys Bosley",
    "Cook": "Duane Amos",
    "Hill": "Shane Knuth",
    "Hinchinbrook": "Nick Dametto",
    "Mundingburra": "Michael Pugh",
    "Townsville": "Margie Ryder",
    "Traeger": "Robbie Katter"
  }
  const IndependentsCandidates= {

    "Bundaberg": "Alan Corbett",
    "Mulgrave": "Yodie Batzke",
    "Noosa": "Sandy Bolton",
    "Rockhampton": "Margaret Strelow",
    "Thuringowa": "Natasha Lane",
    "Townsville": "Wesley Newman"
  }
  const LCQPartyCandidates={
    "Buderim": "Shaun Sandow",
    "Burleigh": "Jason Gann",
    "Caloundra": "Adam Benjamin",
    "Coomera": "Suzette Luyken",
    "Gaven": "Nell Porter",
    "Glass House": "Tim Hallcroft",
    "Hervey Bay": "Jeff Knipe",
    "Logan": "Meredith Brisk",
    "Murrumba": "David Zaloudek",
    "Nicklin": "Melody Lindsay",
    "Ninderry": "Tim Nixon",
    "Pumicestone": "Rosie Doolan",
    "Redlands": "Suzanne Spierenburg",
    "Whitsunday": "Ben Gauci"
  }
  const FFPCandidates = {
    "Ipswich": "Karen Fuller"
  }
  const DLPCandidates={
    "Murrumba": "Scott Donovan"
  }
  const demCandidates = {
    "Sandgate": "Chris Simpson"
  }

export {LaborPartyCandidates, LNPCandidates, greensPartyCandidate, oneNationPartyCandidates,KAPPartyCandidates,IndependentsCandidates,LCQPartyCandidates, FFPCandidates,DLPCandidates,demCandidates}